### PR TITLE
chore(deps): update to the latest versions

### PR DESCRIPTION
**Pull request by fkm**

### CODE REVIEW

**Comment by fkm** [comment]
Does someone understand this error?

I have no problem running the tests locally.

**Comment by anehx** [comment]
Seems a lot like https://github.com/ember-cli/ember-cli-htmlbars/issues/297 which would be weird because you are using the right version of `ember-cli-htmlbars`. Did you run `yarn upgrade`, could it be that the lockfile is somehow wrong?

**Comment by fkm** [comment]
`yarn upgrade` didn't help. I'll try recreating the yarn.lock file after lunch.

**Comment by fkm** [comment]
Couldn't find anything. I give up. Maybe I'll find something along the way. But I'm just wasting time here.

**Pull request closed without merging**
