### PR TITLE
Remove ember-cli-eslint from dependencies

### PR DESCRIPTION
**Pull request by fkm**
Same reason as for the other projects. This causes errors and is not actually necessary.

PS: There's some unrelated refactoring in there.  
`.travis.yml`

### CODE REVIEW

**Comment by czosel** [comment]
Looks like there's a conflict in the lockfile.

**Comment by fkm** [comment]
Yeah. I'm merging the branches from the bot.

This will be resolved shortly.

**Comment by fkm** [comment]
*bump*

**Review by anehx — APPROVED** [review]

**Review by czosel — APPROVED** [review]
LGTM, /cc @anehx

**Comment by czosel** [comment]
Nice timing @anehx :laughing:

**Pull request merged**
